---
abstract: 'When you absolutely B<have> to load that damned package.'
author:
  - "Curtis 'Ovid' Poe <ovid@cpan.org>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Package-Butcher
provides:
  Package::Butcher:
    file: lib/Package/Butcher.pm
    version: 0.01
  Package::Butcher::Inflator:
    file: lib/Package/Butcher/Inflator.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Ovid/Package-Butcher
version: 0.01
